//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment_Type_Question
    {
        public Assessment_Type_Question()
        {
            this.Assessment_Type_Option = new HashSet<Assessment_Type_Option>();
            this.Assessment_Type_Question_Answer = new HashSet<Assessment_Type_Question_Answer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Assessment_Type_Id { get; set; }
        public string Question { get; set; }
        public Nullable<int> Question_Type { get; set; }
    
        public virtual Assessment_Type Assessment_Type { get; set; }
        public virtual ICollection<Assessment_Type_Option> Assessment_Type_Option { get; set; }
        public virtual ICollection<Assessment_Type_Question_Answer> Assessment_Type_Question_Answer { get; set; }
    }
}
