//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment_Type
    {
        public Assessment_Type()
        {
            this.Assessment_Type_Question = new HashSet<Assessment_Type_Question>();
            this.Trial_Participant_Assessment_Type = new HashSet<Trial_Participant_Assessment_Type>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Assessment_Type_Question> Assessment_Type_Question { get; set; }
        public virtual ICollection<Trial_Participant_Assessment_Type> Trial_Participant_Assessment_Type { get; set; }
    }
}
