//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinician
    {
        public Clinician()
        {
            this.Participant_Clinician = new HashSet<Participant_Clinician>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Person_Id { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Participant_Clinician> Participant_Clinician { get; set; }
    }
}
