//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant_Group
    {
        public Participant_Group()
        {
            this.Participant_Group_Intervention_Area = new HashSet<Participant_Group_Intervention_Area>();
            this.Trial_Participant_Participant_Group = new HashSet<Trial_Participant_Participant_Group>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Participant_Group_Intervention_Area> Participant_Group_Intervention_Area { get; set; }
        public virtual ICollection<Trial_Participant_Participant_Group> Trial_Participant_Participant_Group { get; set; }
    }
}
