//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Administrators = new HashSet<Administrator>();
            this.Clinicians = new HashSet<Clinician>();
            this.Investigators = new HashSet<Investigator>();
            this.Participants = new HashSet<Participant>();
        }
    
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Phone_Number { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<Administrator> Administrators { get; set; }
        public virtual ICollection<Clinician> Clinicians { get; set; }
        public virtual ICollection<Investigator> Investigators { get; set; }
        public virtual ICollection<Participant> Participants { get; set; }
    }
}
