//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trial_Participant_Participant_Group
    {
        public int Id { get; set; }
        public Nullable<int> Trial_Participant_Id { get; set; }
        public Nullable<int> Participant_Group_Id { get; set; }
    
        public virtual Participant_Group Participant_Group { get; set; }
        public virtual Trial_Participant Trial_Participant { get; set; }
    }
}
