//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment_Type_Option
    {
        public int Id { get; set; }
        public Nullable<int> Assessment_Type_Question_Id { get; set; }
        public string Opt { get; set; }
    
        public virtual Assessment_Type_Question Assessment_Type_Question { get; set; }
    }
}
