//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PX_Entities : DbContext
    {
        public PX_Entities()
            : base("name=PX_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Assessment_Type> Assessment_Type { get; set; }
        public virtual DbSet<Assessment_Type_Option> Assessment_Type_Option { get; set; }
        public virtual DbSet<Assessment_Type_Question> Assessment_Type_Question { get; set; }
        public virtual DbSet<Assessment_Type_Question_Answer> Assessment_Type_Question_Answer { get; set; }
        public virtual DbSet<Clinician> Clinicians { get; set; }
        public virtual DbSet<Intervention_Area> Intervention_Area { get; set; }
        public virtual DbSet<Intervention_Area_Test> Intervention_Area_Test { get; set; }
        public virtual DbSet<Intervention_Area_Test_Question> Intervention_Area_Test_Question { get; set; }
        public virtual DbSet<Intervention_Area_Test_Question_Answer> Intervention_Area_Test_Question_Answer { get; set; }
        public virtual DbSet<Intervention_Area_Test_Question_Option> Intervention_Area_Test_Question_Option { get; set; }
        public virtual DbSet<Investigator> Investigators { get; set; }
        public virtual DbSet<Investigator_Intervention_Area> Investigator_Intervention_Area { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Participant_Clinician> Participant_Clinician { get; set; }
        public virtual DbSet<Participant_Group> Participant_Group { get; set; }
        public virtual DbSet<Participant_Group_Intervention_Area> Participant_Group_Intervention_Area { get; set; }
        public virtual DbSet<Participant_Screening_Criteria> Participant_Screening_Criteria { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Screening_Criteria> Screening_Criteria { get; set; }
        public virtual DbSet<Screening_Criteria_Option> Screening_Criteria_Option { get; set; }
        public virtual DbSet<Trial> Trials { get; set; }
        public virtual DbSet<Trial_Investigator> Trial_Investigator { get; set; }
        public virtual DbSet<Trial_Participant> Trial_Participant { get; set; }
        public virtual DbSet<Trial_Participant_Assessment_Type> Trial_Participant_Assessment_Type { get; set; }
        public virtual DbSet<Trial_Participant_Intervention_Area_Test> Trial_Participant_Intervention_Area_Test { get; set; }
        public virtual DbSet<Trial_Participant_Participant_Group> Trial_Participant_Participant_Group { get; set; }
        public virtual DbSet<Trial_Screening_Criteria> Trial_Screening_Criteria { get; set; }
    }
}
