//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervention_Area_Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Intervention_Area_Test()
        {
            this.Intervention_Area_Test_Question = new HashSet<Intervention_Area_Test_Question>();
            this.Trial_Participant_Intervention_Area_Test = new HashSet<Trial_Participant_Intervention_Area_Test>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Intervention_Area_Id { get; set; }
        public string Name { get; set; }
    
        public virtual Intervention_Area Intervention_Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intervention_Area_Test_Question> Intervention_Area_Test_Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trial_Participant_Intervention_Area_Test> Trial_Participant_Intervention_Area_Test { get; set; }
    }
}
