//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervention_Area_Test_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Intervention_Area_Test_Question()
        {
            this.Intervention_Area_Test_Question_Option = new HashSet<Intervention_Area_Test_Question_Option>();
            this.Intervention_Area_Test_Question_Answer = new HashSet<Intervention_Area_Test_Question_Answer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Intervention_Area_Test_Id { get; set; }
        public string Question { get; set; }
        public Nullable<int> Question_Type { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        public virtual Intervention_Area_Test Intervention_Area_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intervention_Area_Test_Question_Option> Intervention_Area_Test_Question_Option { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intervention_Area_Test_Question_Answer> Intervention_Area_Test_Question_Answer { get; set; }
    }
}
