//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant_Clinician
    {
        public int Id { get; set; }
        public Nullable<int> Participant_Id { get; set; }
        public Nullable<int> Clinician_Id { get; set; }
    
        public virtual Clinician Clinician { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
