//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trial_Participant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trial_Participant()
        {
            this.Trial_Participant_Participant_Group = new HashSet<Trial_Participant_Participant_Group>();
            this.Trial_Participant_Intervention_Area_Test = new HashSet<Trial_Participant_Intervention_Area_Test>();
            this.Trial_Participant_Assessment_Type = new HashSet<Trial_Participant_Assessment_Type>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Trial_Id { get; set; }
        public Nullable<int> Participant_Id { get; set; }
        public Nullable<int> Classification { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual Trial Trial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trial_Participant_Participant_Group> Trial_Participant_Participant_Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trial_Participant_Intervention_Area_Test> Trial_Participant_Intervention_Area_Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trial_Participant_Assessment_Type> Trial_Participant_Assessment_Type { get; set; }
    }
}
