//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trial_Participant_Assessment_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trial_Participant_Assessment_Type()
        {
            this.Assessment_Type_Question_Answer = new HashSet<Assessment_Type_Question_Answer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Trial_Participant_Id { get; set; }
        public Nullable<int> Assessment_Type_Id { get; set; }
    
        public virtual Assessment_Type Assessment_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assessment_Type_Question_Answer> Assessment_Type_Question_Answer { get; set; }
        public virtual Trial_Participant Trial_Participant { get; set; }
    }
}
