//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trial_Screening_Criteria
    {
        public int Id { get; set; }
        public Nullable<int> Trial_Id { get; set; }
        public Nullable<int> Screening_Criteria_Id { get; set; }
        public Nullable<int> OperatorType { get; set; }
        public string OperatorValue { get; set; }
    
        public virtual Screening_Criteria Screening_Criteria { get; set; }
        public virtual Trial Trial { get; set; }
    }
}
