//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trial_Investigator
    {
        public int Id { get; set; }
        public Nullable<int> Investigator_Id { get; set; }
        public Nullable<int> Trial_Id { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Investigator Investigator { get; set; }
        public virtual Trial Trial { get; set; }
    }
}
